Description: "Creates a Linux operator machine."
Mappings:
  Images:
    us-east-1:
      Id: "ami-04505e74c0741db8d"
Resources:
  OperatorKeyPair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: tdp-operator-keypair
  OperatorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-0616056f55547657e
      GroupDescription: Security Group for AMIs
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
  OperatorInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap
        - Images
        - !Ref AWS::Region
        - Id
      InstanceType: "t3.large"
      KeyName: !Ref OperatorKeyPair
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 50
            DeleteOnTermination: true
      SecurityGroupIds:
        - !Ref OperatorSecurityGroup
      Tags:
        - Key: "Name"
          Value: "tdp-operator"
Outputs:
  InstanceId:
    Value: !Ref OperatorInstance
  PublicDnsName:
    Value: !GetAtt OperatorInstance.PublicDnsName
